### PR TITLE
Updated german translation

### PR DESCRIPTION
**Pull request by mezen**
Some translations were just creepy

I also have a question:
Only `<CPI.pawnconvertedrelease>` has a `will be now scheduled for release`, all others have `will be recruited` or `will be enslaved`. Does the "scheduled" have a deeper meaning, or should it maybe be better unified? If yes, the german sentence should be `<CPI.pawnconvertedrelease>{0} wurde konvertiert und wird nun freigelassen</CPI.pawnconvertedrelease>`

### CODE REVIEW

**Comment by mezen** [comment]
@emipa606 any chance to get the correct german translation?

**Comment by emipa606** [comment]
Updating all my mods, Ill get to mod additions/changes after Im done with the 1.4 updates.

**Comment by emipa606** [comment]
Should be added in 3dd3c91 thank you!

**Comment by mezen** [comment]
Have you managed to deal with my question yet?

**Comment by emipa606** [comment]
Sorry, missed that. The scheduled is used as it sounded better in the message when the pawn gets healty.

**Pull request merged**
